//
//  ShowDetailInteractor.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 24/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailBusinessLogic{
    func getDetails(request: ShowDetail.GetDetails.Request)
    func getSongList(request: ShowDetail.GetSongList.Request)
}

protocol ShowDetailDataStore{
    var song: Song! { get set }
    var songs: [Song]!{ get set }
}

class ShowDetailInteractor: ShowDetailBusinessLogic, ShowDetailDataStore{
    var presenter: ShowDetailPresentationLogic?
    var worker: ShowDetailWorker?
    var song: Song!
    var songs: [Song]!
    
    // MARK: Do something
    
    func getDetails(request: ShowDetail.GetDetails.Request){
        worker = ShowDetailWorker()
        let response = ShowDetail.GetDetails.Response(song: song)
        presenter?.presentDetails(response: response)
    }
    
    func getSongList(request: ShowDetail.GetSongList.Request){
        worker?.getSongList(song.collectionId!, completion: { (results) -> Void in
            self.songs = results!
            let response = ShowDetail.GetSongList.Response(songs: self.songs)
            self.presenter?.presentSongList(response: response)
        })
    }
}
