//
//  ShowDetailPresenter.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 24/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailPresentationLogic
{
  func presentDetails(response: ShowDetail.GetDetails.Response)
    func presentSongList(response: ShowDetail.GetSongList.Response)
}

class ShowDetailPresenter: ShowDetailPresentationLogic
{
  weak var viewController: ShowDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentDetails(response: ShowDetail.GetDetails.Response)
  {
    let artWork = response.song.artworkUrl100 ?? response.song.artworkUrl60
    
    
    let viewModel = ShowDetail.GetDetails.ViewModel(
        album: response.song.collectionName!,
        banda:response.song.artistName!,
        nombreCancion: response.song.trackName!,
        previewUrl: response.song.previewUrl!,
        artWorkUrl: artWork!
    )
    viewController?.displayDetails(viewModel: viewModel)
 
  }
    
    func presentSongList(response: ShowDetail.GetSongList.Response){
        let viewModel = ShowDetail.GetSongList.ViewModel(songs: response.songs)
        viewController?.displaySongList(viewModel: viewModel)
    }
}
