//
//  SearchPresenter.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 23/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentSearchResults(response: Search.FetchResults.Response)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSearchResults(response: Search.FetchResults.Response)
    {
        let viewModel = Search.FetchResults.ViewModel(displayedResults: response.results)
        viewController?.displayResults(viewModel:viewModel)
    }
}
