//
//  SearchModels.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 23/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
    enum FetchResults{
        struct Request
        {
            var query:String
        }
        struct Response
        {
          var results: [Song]
        }
        struct ViewModel
        { 
          var displayedResults: [Song]
        }
        
    }
}
