//
//  SearchWorker.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 23/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class SearchWorker{
    
    let decoder = JSONDecoder()
    func fetchResults(_ query: String,completion: @escaping ([Song]?) -> Void)
  {
    
    guard let url = URL(string: "https://itunes.apple.com/search?") else {
      completion(nil)
      return
    }
    
    AF.request(url,
               parameters: ["term":query,
                            "media":"music",
                            "limit":"20",
                            "attribute":"songTerm"]
               ).responseData { response in
       switch response.result {
        case .success(let value):
            do {
                let fetchResults = try self.decoder.decode(FetchSongs.self , from: value)
                // se filtran los resultados para evitar que vengan caciones sin Album
                let response = fetchResults.results.filter({(song) -> Bool in
                    return song.collectionId != nil
                })
                completion(response)
            }catch {
                print("JSONSerialization error:", error)
            }
           return
        case .failure(let error):
            print(error)
            completion(nil)
            return
        }
        
    }
    
  }
 
}
