//
//  SearchInteractor.swift
//  ItunesApiSearch
//
//  Created by Harold Campuzano Rivera on 23/12/19.
//  Copyright (c) 2019 harold-campuzano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
  func search(request: Search.FetchResults.Request)
}

protocol SearchDataStore
{
  //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
  var presenter: SearchPresentationLogic?
  var worker: SearchWorker?
  
  var results:  [Result]?
  
  // MARK: Do search
  
  func search(request: Search.FetchResults.Request){
    worker = SearchWorker()
    worker?.fetchResults(request.query, completion: { (results) -> Void in
      self.results = results!
      let response = Search.FetchResults.Response(results: results!)
      self.presenter?.presentSearchResults(response: response)
    })
  }
}
